name: Update README with Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v3  # Updated to v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install matplotlib requests

      - name: Run data fetch script
        run: python generate_charts.py

      - name: Update README
        run: |
          mv activity_chart.png ./activity_chart.png
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add activity_chart.png
          git commit -m "Update activity chart"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
